export const userMap = {
	인제군: 'inje',
	양구군: 'yanggu',
	삼척시: 'samcheok',
	동해시: 'donghae',
	강릉시: 'gangneung',
	춘천시: 'chuncheon',
	횡성군: 'hoengseong',
	영월군: 'yeongwol',
	홍천군: 'hongcheon',
	정선군: 'jeongseon',
	평창군: 'pyeongchang',
	태백시: 'taebaek',
	속초시: 'sokcho',
	양양군: 'yangyang',
	고성군: 'goseong',
	원주시: 'wonju',
	화천군: 'hwacheon',
	철원군: 'cheorwon',
};
